apiVersion: v1
kind: Pod
spec:
  containers:
    - name: maven
      image: maven:3.5.4-jdk-8-slim
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
      resources:
        requests:
          memory: "4Gi"
          cpu: "125m"
        limits:
          memory: "4Gi"
